"""Constants for FBI Crime Data Explorer API."""

from pathlib import Path

BASE_URL = "https://api.usa.gov/crime/fbi/cde"
CACHE_DIR = Path.home() / ".cache" / "fbi-crime-data-mcp"
SPILLOVER_DIR = CACHE_DIR / "spillover"
STATS_FILE = CACHE_DIR / "stats.json"
SPILLOVER_CHAR_LIMIT = 128_000
SPILLOVER_PREVIEW_CHARS = 2_000

# Summarized (SRS) offense codes
SRS_OFFENSES: dict[str, str] = {
    "V": "Violent Crime",
    "P": "Property Crime",
    "HOM": "Homicide",
    "RPE": "Rape",
    "ROB": "Robbery",
    "ASS": "Aggravated Assault",
    "BUR": "Burglary",
    "LAR": "Larceny-Theft",
    "MVT": "Motor Vehicle Theft",
    "ARS": "Arson",
}

# NIBRS offense codes (UCR codes)
NIBRS_OFFENSES: dict[str, str] = {
    "09A": "Murder and Nonnegligent Manslaughter",
    "09B": "Negligent Manslaughter",
    "09C": "Justifiable Homicide",
    "100": "Kidnapping/Abduction",
    "11A": "Rape",
    "11B": "Sodomy",
    "11C": "Sexual Assault With An Object",
    "11D": "Fondling",
    "120": "Robbery",
    "13A": "Aggravated Assault",
    "13B": "Simple Assault",
    "13C": "Intimidation",
    "200": "Arson",
    "210": "Extortion/Blackmail",
    "220": "Burglary/Breaking & Entering",
    "23A": "Pocket-picking",
    "23B": "Purse-snatching",
    "23C": "Shoplifting",
    "23D": "Theft From Building",
    "23E": "Theft From Coin-Operated Machine or Device",
    "23F": "Theft From Motor Vehicle",
    "23G": "Theft of Motor Vehicle Parts or Accessories",
    "23H": "All Other Larceny",
    "240": "Motor Vehicle Theft",
    "250": "Counterfeiting/Forgery",
    "26A": "False Pretenses/Swindle/Confidence Game",
    "26B": "Credit Card/Automated Teller Machine Fraud",
    "26C": "Impersonation",
    "26D": "Welfare Fraud",
    "26E": "Wire Fraud",
    "26F": "Identity Theft",
    "26G": "Hacking/Computer Invasion",
    "26H": "Money Laundering",
    "270": "Embezzlement",
    "280": "Stolen Property Offenses",
    "290": "Destruction/Damage/Vandalism of Property",
    "30A": "Betting/Wagering",
    "30B": "Operating/Promoting/Assisting Gambling",
    "30C": "Gambling Equipment Violations",
    "30D": "Sports Tampering",
    "35A": "Drug/Narcotic Violations",
    "35B": "Drug Equipment Violations",
    "36A": "Incest",
    "36B": "Statutory Rape",
    "360": "Sex Offenses - Nonforcible (pre-2018)",
    "370": "Pornography/Obscene Material",
    "39A": "Betting/Wagering",
    "39B": "Operating/Promoting/Assisting Gambling",
    "39C": "Gambling Equipment Violations",
    "39D": "Sports Tampering",
    "40A": "Prostitution",
    "40B": "Assisting or Promoting Prostitution",
    "40C": "Purchasing Prostitution",
    "510": "Bribery",
    "520": "Weapon Law Violations",
    "521": "Firearm Act Violation",
    "522": "Weapons of Mass Destruction",
    "526": "Violation of National Firearms Act of 1934",
    "58A": "Human Trafficking, Commercial Sex Acts",
    "58B": "Human Trafficking, Involuntary Servitude",
    "61A": "Federal Liquor Offenses",
    "61B": "State Liquor Law Violations",
    "620": "Disorderly Conduct",
    "64A": "Human Trafficking, Commercial Sex Acts",
    "64B": "Human Trafficking, Involuntary Servitude",
    "720": "Animal Cruelty",
    "49A": "Curfew/Loitering/Vagrancy Violations",
    "49B": "Trespass of Real Property",
    "49C": "Runaway",
    "101": "Unknown",
    "103": "Unknown",
}

# Arrest offense codes
ARREST_OFFENSES: dict[str, str] = {
    "all": "All Offenses",
    "11": "Murder and Nonnegligent Homicide",
    "12": "Manslaughter by Negligence",
    "20": "Rape - Not Specified (Legacy)",
    "23": "Rape",
    "30": "Robbery",
    "50": "Assault - Not Specified",
    "55": "Simple Assault",
    "60": "Burglary",
    "70": "Larceny - Theft",
    "90": "Motor Vehicle Theft",
    "101": "Human Trafficking - Commercial Sex Acts",
    "102": "Human Trafficking - Involuntary Servitude",
    "110": "Arson",
    "140": "Prostitution and Commercialized Vice",
    "141": "Prostitution",
    "142": "Prostitution - Assisting or Promoting",
    "143": "Prostitution - Purchasing",
    "150": "Drug Abuse Violations",
    "151": "Drug Sale/Manufacturing (Unspecified)",
    "152": "Drug Sale/Manufacturing - Opium or Cocaine",
    "153": "Drug Sale/Manufacturing - Marijuana",
    "154": "Drug Sale/Manufacturing - Synthetic Narcotics",
    "155": "Drug Sale/Manufacturing - Other",
    "156": "Drug Possession (Unspecified)",
    "157": "Drug Possession - Opium or Cocaine",
    "158": "Drug Possession - Marijuana",
    "159": "Drug Possession - Synthetic Narcotics",
    "160": "Drug Possession - Other",
    "170": "Gambling (Unspecified)",
    "171": "Gambling - Bookmaking",
    "172": "Gambling - Numbers and Lottery",
    "173": "Gambling - All Other",
    "180": "Forgery and Counterfeiting",
    "190": "Fraud",
    "200": "Embezzlement",
    "210": "Stolen Property",
    "220": "Vandalism",
    "230": "Weapons: Carrying, Possessing, Etc.",
    "240": "Sex Offenses",
    "250": "Offenses Against the Family and Children",
    "260": "Driving Under the Influence",
    "270": "Liquor Law Violations",
    "280": "Drunkenness",
    "290": "Disorderly Conduct",
    "300": "Vagrancy",
    "310": "All Other Offenses (Except Traffic)",
    "330": "Curfew and Loitering Law Violations",
}

# Hate crime bias codes
BIAS_CODES: dict[str, str] = {
    "all": "All Biases",
    "11": "Anti-White",
    "12": "Anti-Black or African American",
    "13": "Anti-American Indian or Alaska Native",
    "14": "Anti-Asian",
    "15": "Anti-Multi-Racial Group",
    "16": "Anti-Native Hawaiian or Other Pacific Islander",
    "21": "Anti-Jewish",
    "22": "Anti-Catholic",
    "23": "Anti-Protestant",
    "24": "Anti-Islamic (Muslim)",
    "25": "Anti-Other Religion",
    "26": "Anti-Multi-Religious Group",
    "27": "Anti-Atheism/Agnosticism",
    "28": "Anti-Church of Jesus Christ",
    "29": "Anti-Jehovah's Witness",
    "31": "Anti-Arab",
    "32": "Anti-Hispanic or Latino",
    "33": "Anti-Other Race/Ethnicity/Ancestry",
    "41": "Anti-Male Homosexual (Gay)",
    "42": "Anti-Lesbian",
    "43": "Anti-LGBT Mixed Group",
    "44": "Anti-Heterosexual",
    "45": "Anti-Bisexual",
    "51": "Anti-Physical Disability",
    "52": "Anti-Mental Disability",
    "61": "Anti-Male",
    "62": "Anti-Female",
    "71": "Anti-Transgender",
    "72": "Anti-Gender Non-Conforming",
    "81": "Anti-Eastern Orthodox",
    "82": "Anti-Other Christian",
    "83": "Anti-Buddhist",
    "84": "Anti-Hindu",
    "85": "Anti-Sikh",
}

# Expanded property (supplemental) offense codes
SUPPLEMENTAL_OFFENSES: dict[str, str] = {
    "NB": "Burglary",
    "NL": "Larceny",
    "NMVT": "Motor Vehicle Theft",
    "NROB": "Robbery",
}

# LESDC chart types
LESDC_CHART_TYPES: dict[str, str] = {
    "demographics": "Demographics",
    "race": "Race",
    "location": "Location",
    "duty": "Duty Status",
    "manner": "Manner",
    "employment": "Employment",
    "occupation": "Occupation",
    "military": "Military",
    "totals": "Totals",
    "exp": "Experience",
    "expfollowing": "Experience Following",
    "experience": "Experience Detail",
    "suffered": "Suffered",
    "prior": "Prior",
    "investigation": "Investigation",
    "wellness": "Wellness",
}

# NIBRS estimation regions
NIBRS_REGIONS: dict[str, str] = {
    "M": "Midwest",
    "N": "Northeast",
    "S": "South",
    "W": "West",
}

# NIBRS estimation size groups
NIBRS_SIZE_GROUPS: dict[str, str] = {
    "1": "Cities 250,000 or over",
    "2": "Cities from 100,000 thru 249,999",
    "3": "Cities from 10,000 thru 24,999",
    "4": "Cities from 25,000 thru 49,999",
    "5": "Cities from 50,000 thru 99,999",
    "6": "Cities under 10,000",
    "7": "MSA Counties",
    "8": "Non-MSA Counties",
}

# US states and territories
US_STATES: dict[str, str] = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming",
    "DC": "District of Columbia",
    "AS": "American Samoa",
    "GU": "Guam",
    "MP": "Northern Mariana Islands",
    "PR": "Puerto Rico",
    "VI": "Virgin Islands",
}
